# This file contains the packages used in the script 3_analysis

rm(list=ls())

#install necessary packages
install.packages("bipartite")
install.packages("vegan")
install.packages("nlme")
install.packages("lme4")
install.packages("lmerTest")
install.packages("tidyverse")
install.packages("tnet")
install.packages("bmotif")
install.packages("sciplot")
install.packages("ggtheme")
install.packages("ggplot2")
install.packages("viridis")
install.packages("evolvability")
install.packages("MuMIn")

#load libraries
library(bipartite)
library(vegan)
library(nlme)
library(lme4)
library(lmerTest)
library(tidyverse)
library(tnet)
library(bmotif)
library(sciplot)
library(ggtheme)
library(ggplot2)
library(viridis)
library(evolvability)
library(MuMIn)
